title: Advanced App Inventor Sushi Cards for Social Innovation
hero_image: images/banner.png
description: Build an Android app that records specific locations and gives directions
theme: green
listed: true
copyedit: true
curriculum: ''
interests: ''
technologies: ''
site_areas: coderdojo, projects
hardware: ''
software: ''
version: 3.0.0
last_tested: "2018-05-04"
steps:
  - title: Introduction
  - title: Creating the layout
  - title: Getting the user's location
  - title: Saving data to Firebase
  - title: Displaying data in the ListView
  - title: Working out the distance between two locations
  - title: Implementing a procedure to work out distances
  - title: Filtering by distance
  - title: Showing locations in a maps app
  - title: Wrapping Up
