title: Advanced App Inventor Sushi Cards
hero_image: images/banner.png
description: Build an Android app that records specific locations and gives directions
theme: green
version: 1
listed: true
copyedit: true
last_tested: "2018-05-04"
steps:
  - title: Introduction
  - title: What you will need
  - title: Creating the layout
  - title: Getting the user's location
  - title: Saving data to Firebase
  - title: Displaying data in the ListView
  - title: Working out the distance between two locations
  - title: Implementing a procedure to work out distances
  - title: Filtering by distance
  - title: Showing locations in a maps app
  - title: Wrapping Up
